import { readFileSync } from 'node:fs'
import { expect, it } from 'vitest'
import { normalizeObservedEvent } from './event-decoder.mjs'
import { normalizeTreasuryState } from './economics/treasury.mjs'

// Generated by the protocol's scripts/capture-driver-integers.mjs, using Rust
// RKYV fixtures and the built Forge drivers (dusk-data-driver 0.3.1) loaded by @dusk/w3sper, including JSON.parse.
const fixture = JSON.parse(readFileSync(new URL('./test-fixtures/driver-integers.json', import.meta.url), 'utf8'))
const observedAt = '2026-10-03T00:00:00.000Z'
const contract = { key: 'treasury', contractId: '66'.repeat(32) }

it('normalizes the real driver treasury event and output without rounding totals', () => {
  const { event } = normalizeObservedEvent({ contract, observedAt, eventName: fixture.event.topic, event: fixture.event.decoded })
  expect(event).toMatchObject({
    amountLux: 999999523162842, totalReceivedLux: '9999995231628421',
    availableLux: '9999995231628419', registrationReceivedLux: '9999995231628417',
    renewalReceivedLux: 3, otherReceivedLux: 1,
  })
  expect(normalizeTreasuryState(fixture.output.decoded)).toMatchObject({
    totalReceivedLux: '9999995231628421', availableLux: '9999995231628419',
    referralClaimableLux: '9999995231628415', referralClaimedLux: '18446744073709551615', referralCount: 10,
  })
})

it.each([
  ['name_registered', { node: [1], label: 'aurora', actor: [2], owner: [2], fee_lux: 110, premium_lux: 100, expires_at: 50, grace_ends_at: 60 }],
  ['fee_config_updated', { config: { three_char_year_lux: 150000000000, four_char_year_lux: 50000000000,
    five_plus_year_lux: 10000000000, referral_reward_bps: 2000, renewal_referral_reward_bps: 1000,
    premium_referral_reward_bps: 0, premium_start_lux: 1000000000000000, version: 2, updated_at: 10 } }],
  ['domain_auction_created', { reserve_price_lux: 100, duration_blocks: 10, start_deadline: 20, fee_bps: 250, created_at: 10 }],
  ['referral_reward_accrued', { amount_lux: 100, claimable_lux: 200, claimed_lux: 0, referral_count: 2 }],
])('accepts string integers throughout a %s event', (eventName, event) => {
  const decode = event => normalizeObservedEvent({ contract, eventName, event, observedAt, observedBlockHeight: 10 })
  // Stringify scalar integer fields; the upstream change preserves byte arrays.
  const strings = JSON.parse(JSON.stringify(event, function (_key, value) {
    return typeof value === 'number' && !Array.isArray(this) ? String(value) : value
  }))
  expect(decode(strings)).toEqual(decode(event))
})

it.each(['version', 'start_deadline', 'expires_at', 'fee_lux', 'referral_count', 'index', 'offer_id'])('rejects malformed and unsafe string integers in %s', key => {
  for (const value of ['9007199254740992', '-1', '1.5', '1e3', '', ' 1', '+1']) {
    expect(() => normalizeObservedEvent({ contract, observedAt, eventName: 'name_registered', event: { [key]: value } }))
      .toThrow(`event.${key} contains an unsafe numeric value`)
  }
})
