import type { DuskDomainContractMap } from './callTypes'

export const DUSK_DOMAINS_PLACEHOLDER_CONTRACT_ID = '0x0000000000000000000000000000000000000000000000000000000000000000'

export const DUSK_DOMAINS_CONTRACTS: DuskDomainContractMap = {
  core: {
    contractId: DUSK_DOMAINS_PLACEHOLDER_CONTRACT_ID,
    driverUrl: '/contracts/dusk-domains-core.data-driver.wasm',
    name: 'Dusk Domains Core',
    methodSigs: {
      init: 'init(InitCoreRuntime)',
      set_referral_config_runtime: 'set_referral_config_runtime(SetReferralConfigRuntime)',
      set_fee_config_runtime: 'set_fee_config_runtime(SetFeeConfigRuntime)',
      commit_runtime: 'commit_runtime(CommitRegistrationRuntime)',
      complete_registration_runtime: 'complete_registration_runtime(CompleteRegistrationRuntime)',
      renew_runtime: 'renew_runtime(RenewNameRuntime)',
      update_authorities_runtime: 'update_authorities_runtime(UpdateAuthoritiesRuntime)',
      escrow_fixed_sale_runtime: 'escrow_fixed_sale_runtime(EscrowFixedSaleRuntime)',
      escrow_auction_runtime: 'escrow_auction_runtime(EscrowAuctionRuntime)',
      accept_marketplace_offer_runtime: 'accept_marketplace_offer_runtime(AcceptMarketplaceOfferRuntime)',
      set_record_sender_runtime: 'set_record_sender_runtime(SetRecordSenderRuntime)',
      clear_record_sender_runtime: 'clear_record_sender_runtime(ClearRecordSenderRuntime)',
      mutate_records_sender_runtime: 'mutate_records_sender_runtime(MutateRecordsSenderRuntime)',
      set_primary_name_runtime: 'set_primary_name_runtime(SetPrimaryNameRuntime)',
      clear_primary_name_runtime: 'clear_primary_name_runtime(ClearPrimaryNameRuntime)',
      create_subname_runtime: 'create_subname_runtime(CreateSubnameRuntime)',
      get_name: 'get_name(GetName)',
      read_record: 'read_record(ReadRecord)',
      read_primary_name: 'read_primary_name(ReadPrimaryName)',
      pending_commitment: 'pending_commitment(PendingCommitmentQuery)',
      fee_config: 'fee_config',
    },
  },
  treasury: {
    contractId: DUSK_DOMAINS_PLACEHOLDER_CONTRACT_ID,
    driverUrl: '/contracts/dusk-domains-treasury.data-driver.wasm',
    name: 'Dusk Domain Treasury',
    methodSigs: {
      init: 'init(InitTreasury)',
      update_operator_runtime: 'update_operator_runtime(UpdateTreasuryOperatorRuntime)',
      claim_runtime: 'claim_runtime(ClaimTreasuryRuntime)',
      claim_all_runtime: 'claim_all_runtime',
      claim_referral_reward_runtime: 'claim_referral_reward_runtime(ClaimReferralRewardRuntime)',
      claim_all_referral_rewards_runtime: 'claim_all_referral_rewards_runtime(ClaimAllReferralRewardsRuntime)',
      read_state: 'read_state',
    },
  },
  marketplace: {
    contractId: DUSK_DOMAINS_PLACEHOLDER_CONTRACT_ID,
    driverUrl: '/contracts/dusk-domains-marketplace.data-driver.wasm',
    name: 'Dusk Domains Marketplace',
    methodSigs: {
      init: 'init(InitMarketplace)',
      set_fee_runtime: 'set_fee_runtime(SetMarketplaceFeeRuntime)',
      update_operator_runtime: 'update_operator_runtime(UpdateMarketplaceOperatorRuntime)',
      buy_fixed_sale_runtime: 'buy_fixed_sale_runtime(BuyFixedSaleRuntime)',
      cancel_fixed_sale_runtime: 'cancel_fixed_sale_runtime(CancelFixedSaleRuntime)',
      expire_fixed_sale_runtime: 'expire_fixed_sale_runtime(ExpireFixedSaleRuntime)',
      place_bid_runtime: 'place_bid_runtime(PlaceBidRuntime)',
      cancel_auction_runtime: 'cancel_auction_runtime(CancelAuctionRuntime)',
      expire_auction_runtime: 'expire_auction_runtime(ExpireAuctionRuntime)',
      settle_auction_runtime: 'settle_auction_runtime(SettleAuctionRuntime)',
      place_offer_runtime: 'place_offer_runtime(PlaceOfferRuntime)',
      cancel_offer_runtime: 'cancel_offer_runtime(CancelOfferRuntime)',
      expire_offer_runtime: 'expire_offer_runtime(ExpireOfferRuntime)',
      claim_refund_runtime: 'claim_refund_runtime(ClaimRefundRuntime)',
      read_config: 'read_config',
      read_fixed_sale: 'read_fixed_sale(ReadFixedSale)',
      read_auction: 'read_auction(ReadAuction)',
      read_offer: 'read_offer(ReadOffer)',
      read_refund: 'read_refund(ReadRefund)',
    },
  },
}
